ALTER TABLE Tipos_de_gaitas
ADD Tipo_de_gaitas UNIQUEIDENTIFIER NOT NULL
PRIMARY KEY NONCLUSTERED DEFAULT NEWID()
GO
ALTER TABLE Tipos_de_gaitas
ALTER COLUMN Tipo_de_gaitas ADD ROWGUIDCOL
GO
ALTER TABLE Tipos_de_gaitas
ADD Imagen VARBINARY(MAX) FILESTREAM NULL
GO 