DROP DATABASE IF EXISTS Gaitas_Row
GO 
CREATE DATABASE Gaitas_Row
GO 
USE Gaitas_Row
GO 
CREATE USER Becario WITHOUT LOGIN 
GO 
CREATE USER Jefe WITHOUT LOGIN 
GO
CREATE TABLE alum_tar(
    ID int PRIMARY KEY NOT NULL,
    NIF CHAR(9) NOT NULL,
    Numero VARCHAR(30) NOT NULL,
    CVC CHAR(3) NOT NULL,
    Caducidad DATE NOT NULL,
    Telefono int NOT NULL
)