USE Gaitas_Enc
GO 
CREATE TABLE Alumnos2(
    ID int PRIMARY KEY NONCLUSTERED,
    Nombre VARCHAR(50) NOT NULL,
    DNI VARBINARY(128) NOT NULL
)
GO
SELECT ID, Nombre, CONVERT(VARCHAR(50),DECRYPTBYPASSPHRASE('abc123..',DNI)) as NIF FROM Alumnos2
GO